


import {
  CustomSelect,
  CustomInput,
  PhotoCapture,
  CustomSelects,
  ProductTypeSelection,
} from "../components/InputComp";
 const formFieldsConfig = useMemo(() => {
    const baseFields = [
      {
        name: "product",
        label: "Product",
        type: "select",
        component: CustomSelects,
        options: productDetails,
        visible: true,
        span: 1,
      },
      {
        name: "productName",
        label: "Product Name",
        type: "input",
        component: CustomInput,
        visible: false,
        span: 1,
      },
      {
        name: "pieces",
        label: "Pieces",
        type: "input",
        component: CustomInput,
        visible: true,
        span: 1,
      },
      {
        name: "productWeightage",
        label: "Product Weightage",
        type: "select",
        component: CustomSelect,
        options: [
          { label: "Gram", value: "Gram" },
          { label: "Pcs", value: "Pcs" },
        ],
        visible: formData.metal_type === "Silver",
        span: 1,
      },
      {
        name: "rate",
        label: "Rate",
        type: "input",
        component: CustomInput,
        visible: formData.metal_type === "Silver" && formData?.productWeightage?.value === "Pcs",
        span: 1,
      },
      {
        name: "grossWt",
        label: "Gross Weight",
        type: "input",
        component: CustomInput,
        visible: true,
        span: 1,
      },
      {
        name: "diacent",
        label: "Diamond Carat",
        type: "input",
        component: CustomInput,
        visible: selectedTypes.Diamond,
        span: 1,
      },
      {
        name: "stoneWt",
        label: "Stone Weight in (gm)",
        type: "input",
        component: CustomInput,
        visible: true,
        span: 1,
      },
      {
        name: "stoneCost",
        label: "Stone Cost",
        type: "input",
        component: CustomInput,
        visible: true,
        span: 1,
      },
      {
        name: "waxWt",
        label: "Wax Weight",
        type: "input",
        component: CustomInput,
        visible: true,
        span: 1,
      },
      {
        name: "goldwt",
        label: "Gold Net Wt",
        type: "input",
        component: CustomInput,
        visible: selectedTypes.Gold && selectedTypes.Platinum,
        span: 1,
      },
      {
        name: "platinumWt",
        label: "Platinum Grs Wt",
        type: "input",
        component: CustomInput,
        visible: selectedTypes.Gold && selectedTypes.Platinum,
        span: 1,
      },
      {
        name: "netWt",
        label: selectedTypes.Platinum ? "Platinum Net Wt" : "Net Weight",
        type: "input",
        component: CustomInput,
        visible: true,
        disabled: !selectedTypes.Platinum,
        span: 1,
      },
      {
        name: "amount",
        label: "Amount",
        type: "input",
        component: CustomInput,
        visible: true,
        span: 1,
      },
      {
        name: "melting",
        label: selectedTypes.Gold && selectedTypes.Platinum ? "Gold Melting" : "Melting",
        type: "select",
        component: CustomSelect,
        options: meltingOptions,
        visible: formData?.productWeightage?.value === "Gram" || formData.metal_type === "Gold" || selectedTypes.Gold,
        span: 1,
      },
      {
        name: "wastage",
        label: "Wastage",
        type: "select",
        component: CustomSelect,
        options: wastageOptions,
        visible: (formData?.productWeightage?.value === "Gram" || formData.metal_type === "Gold") && !selectedTypes.Diamond && !selectedTypes.Platinum,
        span: 1,
      },
      {
        name: "mc",
        label: "Making Charges",
        type: "input",
        component: CustomInput,
        visible: (formData?.productWeightage?.value === "Gram" || formData.metal_type === "Gold") && !selectedTypes.Diamond && !selectedTypes.Platinum,
        span: 1,
      },
      {
        name: "pureWt",
        label: selectedTypes.Gold && selectedTypes.Platinum ? "Gold PureWt" : "PureWt",
        type: "input",
        component: CustomInput,
        visible: formData.metal_type !== "Silver" && (!selectedTypes.Platinum || selectedTypes.Gold),
        disabled: true,
        span: 1,
      },
    ];

    return baseFields.filter((field) => field.visible);
  }, [
    formData,
    selectedTypes,
    productDetails,
    meltingOptions,
    wastageOptions,
  ]);
